-- ZOEZONE — seed data generated from js/products.js

INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('ash-frayed-jacket', 'Ash Frayed Hooded Jacket', 'The New Era', ARRAY['outerwear'], '{}', 99.0, NULL, ARRAY['gray'], ARRAY['S','M','L','XL'], ARRAY['#8d8f92'], NULL, false, NULL, '<div class="garment">
              <div class="hoodie frayed wash-gray">
                <div class="emblem">
                  <svg viewBox="0 0 24 24" fill="none" stroke="rgba(0,0,0,0.4)" stroke-width="1.2"><path d="M12 3v10M8 7l4-4 4 4M6 21c0-4 2-6 6-6s6 2 6 6"/></svg>
                </div>
              </div>
            </div>', 'Statement layering starts here. The Ash Frayed Hooded Jacket pairs a heavyweight fleece build with raw-edge, distressed detailing for a silhouette that feels equal parts streetwear and archive piece. From The New Era collection.', ARRAY['Heavyweight fleece-back cotton blend','Relaxed, oversized fit','Raw-edge, distressed detailing','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('ash-puffer', 'Ash Quilted Puffer', 'The New Era', ARRAY['outerwear'], '{}', 142.0, NULL, ARRAY['gray'], ARRAY['S','M','L','XL'], ARRAY['#8d8f92'], 'New', true, NULL, '<div class="garment">
              <div class="jacket wash-gray"></div>
            </div>', 'Built for the days that call for real cover. The Ash Quilted Puffer is a quilted, insulated layer with a relaxed fit made for stacking over hoodies and tees without feeling bulky. From The New Era collection.', ARRAY['Quilted, insulated shell','Relaxed fit for easy layering','Ribbed collar and cuffs','Made in Haiti','Spot clean or gentle machine wash'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('ash-tribal-tee', 'Ash Wash Tribal Tee', 'The New Era', ARRAY['tops'], '{}', 39.0, 46.0, ARRAY['gray'], ARRAY['S','M','L'], ARRAY['#8d8f92'], NULL, false, NULL, '<img src="assets/tops-look-tribal.png" alt="Ash Wash Tribal Tee" style="width:100%;height:100%;object-fit:contain;">', 'The Ash Wash Tribal Tee brings ZOEZONE''s punk-funk, industrial edge to an everyday essential. Cut from heavyweight cotton with a relaxed, oversized fit and finished with a hand-distressed wash, it''s built to be lived in — on the block, in the studio, wherever you land. Part of The New Era collection.', ARRAY['100% heavyweight cotton jersey','Oversized, boxy fit','Ribbed crewneck collar','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('aviator-sunglasses', 'Aviator Sunglasses', 'Signature', ARRAY['accessories'], '{}', 33.0, NULL, ARRAY['black','gray'], ARRAY['One Size'], ARRAY['#1a1a1a','#8d8f92'], NULL, false, 'background:var(--cream);', '<div class="acc-icon dark">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M2 8l5.5 1 1 6.5h7l1-6.5 5.5-1"/><circle cx="8" cy="13" r="3.2"/><circle cx="16" cy="13" r="3.2"/><line x1="11.2" y1="13" x2="12.8" y2="13"/></svg>
            </div>', 'The Aviator Sunglasses pairs full UV protection with a silhouette that does the talking. Built for year-round wear. From the Signature collection.', ARRAY['UV400 protection lenses','Durable acetate frame','Includes microfiber pouch','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('beanie', 'Ribbed Knit Beanie', 'Signature', ARRAY['accessories'], '{}', 26.0, NULL, ARRAY['cream','black'], ARRAY['One Size'], ARRAY['#ece7de','#1a1a1a'], NULL, false, 'background:var(--cream);', '<div class="acc-icon dark">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M5 20v-6a7 7 0 0 1 14 0v6"/><line x1="4" y1="17" x2="20" y2="17"/><line x1="4" y1="20" x2="20" y2="20"/></svg>
            </div>', 'The Ribbed Knit Beanie is a ribbed knit beanie built for cooler days — snug, stretchy, and finished with subtle ZOEZONE branding. From the Signature collection.', ARRAY['Ribbed knit acrylic blend','One size fits most','Embroidered ZOEZONE branding','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('bold-sunglasses', 'Bold Line Sunglasses', 'Signature', ARRAY['accessories'], '{}', 27.0, 29.0, ARRAY['black'], ARRAY['One Size'], ARRAY['#1a1a1a'], NULL, false, 'background:var(--cream);', '<div class="acc-icon dark">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><circle cx="7.5" cy="12" r="4"/><circle cx="16.5" cy="12" r="4"/><line x1="11.3" y1="11" x2="12.7" y2="11"/><line x1="1" y1="10" x2="3.6" y2="9"/><line x1="23" y1="10" x2="20.4" y2="9"/></svg>
            </div>', 'The Bold Line Sunglasses pairs full UV protection with a silhouette that does the talking. Built for year-round wear. From the Signature collection.', ARRAY['UV400 protection lenses','Durable acetate frame','Includes microfiber pouch','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('cargo-shorts', 'Cargo Utility Shorts', 'Signature', ARRAY['bottoms'], '{}', 52.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<div class="garment">
              <div class="shorts black"></div>
            </div>', 'Warm-weather essentials, never basic. The Cargo Utility Shorts is cut from heavyweight cotton twill in a relaxed above-the-knee fit, made to move with you. From the Signature collection.', ARRAY['Heavyweight cotton twill','Relaxed, above-the-knee fit','Made in Haiti','Machine wash cold'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('chain-necklace', 'Statement Chain Necklace', 'Signature', ARRAY['accessories'], '{}', 22.0, NULL, ARRAY['gold'], ARRAY['One Size'], ARRAY['#c9a860'], NULL, false, 'background:var(--cream);', '<div class="acc-icon dark">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M6 4c0 7 2.5 10 6 10s6-3 6-10"/><circle cx="12" cy="16" r="2.4"/></svg>
            </div>', 'The Statement Chain Necklace is a statement piece built to layer or wear solo — a tarnish-resistant finish means it''s ready for daily rotation. From the Signature collection.', ARRAY['Stainless steel chain','Adjustable length','Tarnish-resistant finish','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('classic-wash-denim', 'Classic Wash Straight Denim', 'The New Era', ARRAY['bottoms'], '{}', 76.0, NULL, ARRAY['denim'], ARRAY['28','30','32'], ARRAY['#a9bccf'], NULL, false, 'background:var(--white);', '<div class="garment">
              <div class="denim">
                <div class="waist"></div>
                <div class="denim-leg left"></div>
              </div>
            </div>', 'The Classic Wash Straight Denim is cut in a wide-leg, relaxed silhouette that stacks perfectly over sneakers. Rigid cotton denim that breaks in and softens with wear, finished with classic five-pocket styling. From The New Era collection.', ARRAY['Rigid cotton denim','Wide-leg, relaxed fit','Five-pocket styling','Made in Haiti','Machine wash cold, inside out'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('cowl-hoodie', 'Draped Cowl Neck Hoodie', 'The New Era', ARRAY['tops'], ARRAY['new-era','bestseller'], 92.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], 'New', true, NULL, '<img src="assets/tops-look-vest.png" alt="Draped Cowl Neck Hoodie" style="width:100%;height:100%;object-fit:contain;">', 'A hooded vest that does double duty as a layering piece and a standalone statement. The Draped Cowl Neck Hoodie is cut oversized from heavyweight cotton fleece, with raw hems and a heritage-inspired graphic front and center. From The New Era collection.', ARRAY['Heavyweight cotton fleece','Sleeveless, oversized silhouette with attached hood','Raw, unfinished hems','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('cream-blazer', 'Cream Tailored Blazer', 'Signature', ARRAY['tops','outerwear'], '{}', 128.0, NULL, ARRAY['cream'], ARRAY['S','M','L'], ARRAY['#ece7de'], NULL, false, NULL, '<img src="assets/tops-look-tribal.png" alt="Cream Tailored Blazer" style="width:100%;height:100%;object-fit:contain;">', 'Tailoring, reimagined. The Cream Tailored Blazer takes the structure of a classic blazer and oversizes it for an elevated, off-duty silhouette — sharp enough for a night out, relaxed enough for everyday. From the Signature collection.', ARRAY['Structured cotton-blend twill','Oversized, relaxed tailoring','Button-front closure','Made in Haiti','Dry clean recommended'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('cream-boxy-tee', 'Cream Heavyweight Boxy Tee', 'Signature', ARRAY['tops'], ARRAY['bestseller'], 35.0, 44.0, ARRAY['cream','black'], ARRAY['XS','S','M','L','XL'], ARRAY['#ece7de','#1a1a1a'], NULL, false, NULL, '<img src="assets/tops-look-emblem.png" alt="Cream Heavyweight Boxy Tee" style="width:100%;height:100%;object-fit:contain;">', 'The Cream Heavyweight Boxy Tee brings ZOEZONE''s punk-funk, industrial edge to an everyday essential. Cut from heavyweight cotton with a relaxed, oversized fit and finished with a hand-distressed wash, it''s built to be lived in — on the block, in the studio, wherever you land. Part of the Signature collection.', ARRAY['100% heavyweight cotton jersey','Oversized, boxy fit','Ribbed crewneck collar','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('cream-puffer', 'Cream Quilted Puffer', 'Signature', ARRAY['outerwear'], '{}', 148.0, NULL, ARRAY['cream'], ARRAY['S','M','L'], ARRAY['#ece7de'], NULL, false, NULL, '<div class="garment">
              <div class="jacket wash-cream"></div>
            </div>', 'Built for the days that call for real cover. The Cream Quilted Puffer is a quilted, insulated layer with a relaxed fit made for stacking over hoodies and tees without feeling bulky. From the Signature collection.', ARRAY['Quilted, insulated shell','Relaxed fit for easy layering','Ribbed collar and cuffs','Made in Haiti','Spot clean or gentle machine wash'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('cream-trouser', 'Cream Wide-Leg Trouser', 'Signature', ARRAY['bottoms'], '{}', 84.0, NULL, ARRAY['cream'], ARRAY['26','28','30','32'], ARRAY['#ece7de'], NULL, false, 'background:var(--charcoal);', '<div class="garment">
              <div class="denim cream">
                <div class="waist"></div>
                <div class="denim-leg left"></div>
              </div>
            </div>', 'The Cream Wide-Leg Trouser is cut in a wide-leg, relaxed silhouette that stacks perfectly over sneakers. Rigid cotton denim that breaks in and softens with wear, finished with classic five-pocket styling. From the Signature collection.', ARRAY['Rigid cotton denim','Wide-leg, relaxed fit','Five-pocket styling','Made in Haiti','Machine wash cold, inside out'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('crew-socks', 'Crew Socks 3-Pack', 'Signature', ARRAY['accessories'], '{}', 16.0, 22.0, ARRAY['gray','black','cream'], ARRAY['One Size'], ARRAY['#8d8f92','#1a1a1a','#ece7de'], NULL, false, 'background:var(--cream);', '<div class="acc-icon dark">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M6 3v9l-2 4a3 3 0 0 0 3 4h4a2 2 0 0 0 2-2v-4l-1-11z"/><path d="M14 3v9l-2 4a3 3 0 0 0 3 4h4a2 2 0 0 0 2-2v-4l-1-11z"/></svg>
            </div>', 'The Crew Socks 3-Pack rounds out the fit from the ground up — combed cotton, cushioned underfoot, sold as a 3-pack. From the Signature collection.', ARRAY['Combed cotton blend','Cushioned footbed','Sold as a 3-pack','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('crossbody-bag', 'Heritage Crossbody Bag', 'Signature', ARRAY['accessories'], '{}', 54.0, NULL, ARRAY['black'], ARRAY['One Size'], ARRAY['#1a1a1a'], NULL, false, 'background:linear-gradient(160deg,#3a3a3a,#141414);', '<div class="acc-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M6 10L3 3"/><path d="M18 10l3-7"/></svg>
            </div>', 'The Heritage Crossbody Bag carries everything you need without breaking the fit. Durable construction, a clean silhouette, and just enough room for the essentials. From the Signature collection.', ARRAY['Durable canvas construction','Interior pocket for essentials','Reinforced straps','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('dark-indigo-denim', 'Dark Indigo Straight Denim', 'The New Era', ARRAY['bottoms'], '{}', 78.0, NULL, ARRAY['denim'], ARRAY['28','30','32','34','36'], ARRAY['#a9bccf'], 'New', true, 'background:var(--white);', '<div class="garment">
              <div class="denim dark">
                <div class="waist"></div>
                <div class="denim-leg left"></div>
              </div>
            </div>', 'The Dark Indigo Straight Denim is cut in a wide-leg, relaxed silhouette that stacks perfectly over sneakers. Rigid cotton denim that breaks in and softens with wear, finished with classic five-pocket styling. From The New Era collection.', ARRAY['Rigid cotton denim','Wide-leg, relaxed fit','Five-pocket styling','Made in Haiti','Machine wash cold, inside out'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('denim-alline-skirt', 'Denim A-Line Skirt', 'Signature', ARRAY['bottoms'], '{}', 58.0, NULL, ARRAY['denim'], ARRAY['S','M','L','XL'], ARRAY['#a9bccf'], NULL, false, 'background:var(--white);', '<div class="garment">
              <div class="skirt denim"></div>
            </div>', 'The Denim A-Line Skirt brings the same raw, industrial attitude as the rest of the drop to a high-waisted, relaxed silhouette. From the Signature collection.', ARRAY['Heavyweight cotton blend','High-waist, relaxed silhouette','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('double-emblem-hoodie', 'Double Emblem Frayed Hoodie', 'Signature', ARRAY['tops'], '{}', 89.0, NULL, ARRAY['gray'], ARRAY['S','M','L','XL'], ARRAY['#8d8f92'], NULL, false, NULL, '<img src="assets/tops-look-emblem.png" alt="Double Emblem Frayed Hoodie" style="width:100%;height:100%;object-fit:contain;">', 'Statement layering starts here. The Double Emblem Frayed Hoodie pairs a heavyweight fleece build with raw-edge, distressed detailing for a silhouette that feels equal parts streetwear and archive piece. From the Signature collection.', ARRAY['Heavyweight fleece-back cotton blend','Relaxed, oversized fit','Raw-edge, distressed detailing','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('frayed-hoodie-vest', 'Raw-Edge Frayed Hoodie Vest', 'The New Era', ARRAY['tops','outerwear'], ARRAY['new-era','bestseller'], 86.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<img src="assets/tops-look-vest.png" alt="Raw-Edge Frayed Hoodie Vest" style="width:100%;height:100%;object-fit:contain;">', 'A hooded vest that does double duty as a layering piece and a standalone statement. The Raw-Edge Frayed Hoodie Vest is cut oversized from heavyweight cotton fleece, with raw hems and a heritage-inspired graphic front and center. From The New Era collection.', ARRAY['Heavyweight cotton fleece','Sleeveless, oversized silhouette with attached hood','Raw, unfinished hems','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('heritage-blazer', 'Heritage Tailored Blazer', 'Signature', ARRAY['outerwear'], '{}', 134.0, NULL, ARRAY['black'], ARRAY['S','M','L'], ARRAY['#1a1a1a'], NULL, false, NULL, '<div class="garment">
              <div class="blazer">
                <div class="graphic-text" style="top:30%;font-size:8px;">EST. HAITI</div>
              </div>
            </div>', 'Tailoring, reimagined. The Heritage Tailored Blazer takes the structure of a classic blazer and oversizes it for an elevated, off-duty silhouette — sharp enough for a night out, relaxed enough for everyday. From the Signature collection.', ARRAY['Structured cotton-blend twill','Oversized, relaxed tailoring','Button-front closure','Made in Haiti','Dry clean recommended'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('heritage-tribal-tee', 'Heritage Tribal Wash Tee', 'The New Era', ARRAY['tops'], ARRAY['new-era','bestseller'], 48.0, NULL, ARRAY['gray','black','cream'], ARRAY['S','M','L','XL'], ARRAY['#8d8f92','#1a1a1a','#ece7de'], 'New', true, NULL, '<img src="assets/tops-look-tribal.png" alt="Heritage Tribal Wash Tee" style="width:100%;height:100%;object-fit:contain;">', 'The Heritage Tribal Wash Tee brings ZOEZONE''s punk-funk, industrial edge to an everyday essential. Cut from heavyweight cotton with a relaxed, oversized fit and finished with a hand-distressed wash, it''s built to be lived in — on the block, in the studio, wherever you land. Part of The New Era collection.', ARRAY['100% heavyweight cotton jersey','Oversized, boxy fit','Ribbed crewneck collar','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('highwaist-skirt', 'High-Waist Skirt', 'Signature', ARRAY['bottoms'], '{}', 60.0, NULL, ARRAY['black'], ARRAY['M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<div class="garment">
              <div class="skirt"></div>
            </div>', 'The High-Waist Skirt brings the same raw, industrial attitude as the rest of the drop to a high-waisted, relaxed silhouette. From the Signature collection.', ARRAY['Heavyweight cotton blend','High-waist, relaxed silhouette','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('longline-puffer', 'Longline Puffer Coat', 'Signature', ARRAY['outerwear'], '{}', 156.0, NULL, ARRAY['black'], ARRAY['M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<div class="garment">
              <div class="jacket" style="filter:brightness(0.9)"></div>
            </div>', 'Built for the days that call for real cover. The Longline Puffer Coat is a quilted, insulated layer with a relaxed fit made for stacking over hoodies and tees without feeling bulky. From the Signature collection.', ARRAY['Quilted, insulated shell','Relaxed fit for easy layering','Ribbed collar and cuffs','Made in Haiti','Spot clean or gentle machine wash'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('mini-backpack', 'Structured Mini Backpack', 'Signature', ARRAY['accessories'], '{}', 68.0, 85.0, ARRAY['black'], ARRAY['One Size'], ARRAY['#1a1a1a'], 'Sale', false, 'background:linear-gradient(160deg,#3a3a3a,#141414);', '<div class="acc-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="8" width="14" height="13" rx="3"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/><rect x="8.5" y="12" width="7" height="3" rx="1"/><line x1="12" y1="17" x2="12" y2="19"/></svg>
            </div>', 'The Structured Mini Backpack is a structured, everyday carry built for the days you need more than just your pockets. From the Signature collection.', ARRAY['Structured canvas construction','Padded interior compartment','Adjustable straps','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('onyx-hoodie', 'Onyx Monkey Emblem Hoodie', 'Signature', ARRAY['tops'], ARRAY['bestseller'], 70.0, 88.0, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<img src="assets/tops-look-emblem.png" alt="Onyx Monkey Emblem Hoodie" style="width:100%;height:100%;object-fit:contain;">', 'Statement layering starts here. The Onyx Monkey Emblem Hoodie pairs a heavyweight fleece build with raw-edge, distressed detailing for a silhouette that feels equal parts streetwear and archive piece. From the Signature collection.', ARRAY['Heavyweight fleece-back cotton blend','Relaxed, oversized fit','Raw-edge, distressed detailing','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('oversized-blazer', 'Oversized Tailored Blazer', 'The New Era', ARRAY['tops','outerwear'], ARRAY['new-era','bestseller'], 116.0, 145.0, ARRAY['black'], ARRAY['S','M','L'], ARRAY['#1a1a1a'], '-20%', false, NULL, '<img src="assets/tops-look-emblem.png" alt="Oversized Tailored Blazer" style="width:100%;height:100%;object-fit:contain;">', 'Tailoring, reimagined. The Oversized Tailored Blazer takes the structure of a classic blazer and oversizes it for an elevated, off-duty silhouette — sharp enough for a night out, relaxed enough for everyday. From The New Era collection.', ARRAY['Structured cotton-blend twill','Oversized, relaxed tailoring','Button-front closure','Made in Haiti','Dry clean recommended'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('palm-hooded-jacket', 'Palm Emblem Hooded Jacket', 'The New Era', ARRAY['outerwear'], '{}', 94.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], 'New', true, NULL, '<div class="garment">
              <div class="hoodie frayed" style="filter:brightness(0.85)">
                <div class="emblem">
                  <svg viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,0.5)" stroke-width="1.2"><path d="M12 21V9M12 9c-3 0-5-2-5-5 2 0 4 1 5 3 1-2 3-3 5-3 0 3-2 5-5 5z"/></svg>
                </div>
              </div>
            </div>', 'Statement layering starts here. The Palm Emblem Hooded Jacket pairs a heavyweight fleece build with raw-edge, distressed detailing for a silhouette that feels equal parts streetwear and archive piece. From The New Era collection.', ARRAY['Heavyweight fleece-back cotton blend','Relaxed, oversized fit','Raw-edge, distressed detailing','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('palm-vest', 'Palm Graphic Sleeveless Vest', 'The New Era', ARRAY['tops','outerwear'], ARRAY['new-era','bestseller'], 49.0, 58.0, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<img src="assets/tops-look-vest.png" alt="Palm Graphic Sleeveless Vest" style="width:100%;height:100%;object-fit:contain;">', 'A hooded vest that does double duty as a layering piece and a standalone statement. The Palm Graphic Sleeveless Vest is cut oversized from heavyweight cotton fleece, with raw hems and a heritage-inspired graphic front and center. From The New Era collection.', ARRAY['Heavyweight cotton fleece','Sleeveless, oversized silhouette with attached hood','Raw, unfinished hems','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('pendant-chain', 'Engraved Pendant Chain', 'Signature', ARRAY['accessories'], '{}', 27.0, NULL, ARRAY['gold'], ARRAY['One Size'], ARRAY['#c9a860'], NULL, false, 'background:var(--cream);', '<div class="acc-icon dark">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M6 4c0 6 2.5 8 6 8s6-2 6-8"/><path d="M12 12v3"/><rect x="9.5" y="15" width="5" height="4" rx="1"/></svg>
            </div>', 'The Engraved Pendant Chain is a ZOEZONE essential — heavyweight construction, a relaxed fit, and the same never-basic attitude as the rest of the drop. From the Signature collection.', ARRAY['Heavyweight cotton construction','Relaxed fit','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('pleated-skirt', 'Pleated Midi Skirt', 'The New Era', ARRAY['bottoms'], ARRAY['new-era'], 64.0, NULL, ARRAY['black'], ARRAY['S','M','L'], ARRAY['#1a1a1a'], NULL, false, NULL, '<div class="garment">
              <div class="skirt pleated"></div>
            </div>', 'The Pleated Midi Skirt brings the same raw, industrial attitude as the rest of the drop to a high-waisted, relaxed silhouette. From The New Era collection.', ARRAY['Heavyweight cotton blend','High-waist, relaxed silhouette','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('puffer-jacket', 'Quilted Puffer Jacket', 'The New Era', ARRAY['outerwear'], ARRAY['new-era'], 138.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], 'New', true, NULL, '<div class="garment">
              <div class="jacket"></div>
            </div>', 'Built for the days that call for real cover. The Quilted Puffer Jacket is a quilted, insulated layer with a relaxed fit made for stacking over hoodies and tees without feeling bulky. From The New Era collection.', ARRAY['Quilted, insulated shell','Relaxed fit for easy layering','Ribbed collar and cuffs','Made in Haiti','Spot clean or gentle machine wash'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('quilted-vest', 'Charcoal Quilted Vest', 'Signature', ARRAY['outerwear'], '{}', 68.0, NULL, ARRAY['gray'], ARRAY['M','L','XL'], ARRAY['#8d8f92'], NULL, false, NULL, '<div class="garment">
              <div class="vest wash-gray">
                <div class="graphic-text dark" style="top:70%;font-size:8px;">ZOE ZONE</div>
              </div>
            </div>', 'A hooded vest that does double duty as a layering piece and a standalone statement. The Charcoal Quilted Vest is cut oversized from heavyweight cotton fleece, with raw hems and a heritage-inspired graphic front and center. From the Signature collection.', ARRAY['Heavyweight cotton fleece','Sleeveless, oversized silhouette with attached hood','Raw, unfinished hems','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('raw-black-denim', 'Raw Black Denim', 'Signature', ARRAY['bottoms'], '{}', 82.0, NULL, ARRAY['black'], ARRAY['28','30','32','34'], ARRAY['#1a1a1a'], NULL, false, 'background:var(--cream);', '<div class="garment">
              <div class="denim black">
                <div class="waist"></div>
                <div class="denim-leg left"></div>
              </div>
            </div>', 'The Raw Black Denim is cut in a wide-leg, relaxed silhouette that stacks perfectly over sneakers. Rigid cotton denim that breaks in and softens with wear, finished with classic five-pocket styling. From the Signature collection.', ARRAY['Rigid cotton denim','Wide-leg, relaxed fit','Five-pocket styling','Made in Haiti','Machine wash cold, inside out'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('relaxed-black-shorts', 'Relaxed Fit Black Shorts', 'Signature', ARRAY['bottoms'], '{}', 46.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], NULL, false, NULL, '<div class="garment">
              <div class="shorts black"></div>
            </div>', 'Warm-weather essentials, never basic. The Relaxed Fit Black Shorts is cut from heavyweight cotton twill in a relaxed above-the-knee fit, made to move with you. From the Signature collection.', ARRAY['Heavyweight cotton twill','Relaxed, above-the-knee fit','Made in Haiti','Machine wash cold'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('shop-the-fit', 'Zone Tee, Jacquard Short + AF1', 'Street Fit', '{}', ARRAY['new-era'], 164.0, NULL, ARRAY['black'], ARRAY['S','M','L','XL'], ARRAY['#1a1a1a'], 'Complete Fit', false, 'background:linear-gradient(160deg,#3a3a3a,#141414);', '<div class="look-combo">
              <div class="look-tee"><div class="graphic-text" style="font-size:8px;top:55%;">ZOE ZONE</div></div>
              <div class="look-shorts"></div>
              <div class="look-shoes"><div class="shoe"></div><div class="shoe"></div></div>
            </div>
          </div>', 'The complete look, no guesswork required. The Zone Tee, Jacquard Short + AF1 bundles a graphic tee, jacquard shorts, and a fresh pair of AF1s into one easy fit — everything styled together and ready to wear. From the Street Fit collection.', ARRAY['Includes tee, shorts, and sneakers','Heavyweight cotton tee and shorts','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('signature-icon-tee', 'Signature Icon Wash Tee', 'Signature', ARRAY['tops'], ARRAY['new-era','bestseller'], 39.0, 52.0, ARRAY['gray','black'], ARRAY['XS','S','M','L','XL'], ARRAY['#8d8f92','#1a1a1a'], 'Sale', false, NULL, '<img src="assets/tops-look-emblem.png" alt="Signature Icon Wash Tee" style="width:100%;height:100%;object-fit:contain;">', 'The Signature Icon Wash Tee brings ZOEZONE''s punk-funk, industrial edge to an everyday essential. Cut from heavyweight cotton with a relaxed, oversized fit and finished with a hand-distressed wash, it''s built to be lived in — on the block, in the studio, wherever you land. Part of the Signature collection.', ARRAY['100% heavyweight cotton jersey','Oversized, boxy fit','Ribbed crewneck collar','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('slate-vest', 'Slate Sleeveless Vest', 'Signature', ARRAY['tops'], '{}', 54.0, NULL, ARRAY['gray','black'], ARRAY['M','L','XL'], ARRAY['#8d8f92','#1a1a1a'], NULL, false, NULL, '<img src="assets/tops-look-vest.png" alt="Slate Sleeveless Vest" style="width:100%;height:100%;object-fit:contain;">', 'A hooded vest that does double duty as a layering piece and a standalone statement. The Slate Sleeveless Vest is cut oversized from heavyweight cotton fleece, with raw hems and a heritage-inspired graphic front and center. From the Signature collection.', ARRAY['Heavyweight cotton fleece','Sleeveless, oversized silhouette with attached hood','Raw, unfinished hems','Made in Haiti','Machine wash cold, hang dry'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('snapback-cap', 'ZoeZone Snapback Cap', 'The New Era', ARRAY['accessories'], ARRAY['new-era'], 32.0, NULL, ARRAY['black'], ARRAY['One Size'], ARRAY['#1a1a1a'], 'New', true, NULL, '<div class="acc-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M4 15a8 8 0 0 1 16 0"/><path d="M2 15h20"/><path d="M16 15c3 0 5 1.1 6 3.2"/></svg>
            </div>', 'Finish the fit. The ZoeZone Snapback Cap is a structured, low-profile cap with embroidered ZOEZONE branding and an adjustable strap for an all-day fit. From The New Era collection.', ARRAY['Structured cotton twill','Adjustable strap, one size fits most','Embroidered ZOEZONE branding','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('studded-belt', 'Studded Leather Belt', 'Signature', ARRAY['accessories'], '{}', 34.0, NULL, ARRAY['black'], ARRAY['S','M','L'], ARRAY['#1a1a1a'], NULL, false, 'background:linear-gradient(160deg,#3a3a3a,#141414);', '<div class="acc-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="10" width="20" height="4" rx="1"/><circle cx="6" cy="12" r="0.8" fill="rgba(255,255,255,0.75)" stroke="none"/><circle cx="10" cy="12" r="0.8" fill="rgba(255,255,255,0.75)" stroke="none"/><circle cx="14" cy="12" r="0.8" fill="rgba(255,255,255,0.75)" stroke="none"/><circle cx="18" cy="12" r="0.8" fill="rgba(255,255,255,0.75)" stroke="none"/></svg>
            </div>', 'The Studded Leather Belt is the finishing touch — built to hold up to daily wear without losing its shape. From the Signature collection.', ARRAY['Durable webbing construction','Adjustable buckle closure','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('tote-bag', 'Canvas Tote Bag', 'The New Era', ARRAY['accessories'], '{}', 38.0, NULL, ARRAY['cream','black'], ARRAY['One Size'], ARRAY['#ece7de','#1a1a1a'], 'New', true, 'background:linear-gradient(160deg,#3a3a3a,#141414);', '<div class="acc-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M7 8h10l1.2 13H5.8z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg>
            </div>', 'The Canvas Tote Bag carries everything you need without breaking the fit. Durable construction, a clean silhouette, and just enough room for the essentials. From The New Era collection.', ARRAY['Durable canvas construction','Interior pocket for essentials','Reinforced straps','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('vintage-cream-shorts', 'Vintage Wash Cream Shorts', 'Signature', ARRAY['bottoms'], '{}', 50.0, NULL, ARRAY['cream'], ARRAY['S','M','L'], ARRAY['#ece7de'], NULL, false, 'background:var(--charcoal);', '<div class="garment">
              <div class="shorts cream"></div>
            </div>', 'Warm-weather essentials, never basic. The Vintage Wash Cream Shorts is cut from heavyweight cotton twill in a relaxed above-the-knee fit, made to move with you. From the Signature collection.', ARRAY['Heavyweight cotton twill','Relaxed, above-the-knee fit','Made in Haiti','Machine wash cold'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('wash-denim-shorts', 'Wash Denim Shorts', 'The New Era', ARRAY['bottoms'], ARRAY['new-era'], 48.0, NULL, ARRAY['denim'], ARRAY['S','M','L','XL'], ARRAY['#a9bccf'], 'New', true, NULL, '<div class="garment">
              <div class="shorts"></div>
            </div>', 'Warm-weather essentials, never basic. The Wash Denim Shorts is cut from heavyweight cotton twill in a relaxed above-the-knee fit, made to move with you. From The New Era collection.', ARRAY['Heavyweight cotton twill','Relaxed, above-the-knee fit','Made in Haiti','Machine wash cold'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('web-belt', 'Utility Web Belt', 'Signature', ARRAY['accessories'], '{}', 24.0, NULL, ARRAY['black'], ARRAY['S','M','L'], ARRAY['#1a1a1a'], NULL, false, 'background:linear-gradient(160deg,#3a3a3a,#141414);', '<div class="acc-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="10" width="20" height="4" rx="1"/><rect x="9" y="8" width="6" height="8" rx="1"/><circle cx="12" cy="12" r="1" fill="rgba(255,255,255,0.75)" stroke="none"/></svg>
            </div>', 'The Utility Web Belt is the finishing touch — built to hold up to daily wear without losing its shape. From the Signature collection.', ARRAY['Durable webbing construction','Adjustable buckle closure','Made in Haiti'])
ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, collection, categories, tags, price, was_price, colors, sizes, swatch_colors, badge, is_new, media_style, art, description, details) VALUES
  ('wide-leg-denim', 'Wide-Leg Light Wash Denim', 'The New Era', ARRAY['bottoms'], ARRAY['new-era'], 59.0, 74.0, ARRAY['denim'], ARRAY['26','28','30','32','34'], ARRAY['#a9bccf'], NULL, false, 'background:var(--white);', '<div class="garment">
              <div class="denim">
                <div class="waist"></div>
                <div class="denim-leg left"></div>
              </div>
            </div>', 'The Wide-Leg Light Wash Denim is cut in a wide-leg, relaxed silhouette that stacks perfectly over sneakers. Rigid cotton denim that breaks in and softens with wear, finished with classic five-pocket styling. From The New Era collection.', ARRAY['Rigid cotton denim','Wide-leg, relaxed fit','Five-pocket styling','Made in Haiti','Machine wash cold, inside out'])
ON CONFLICT (id) DO NOTHING;

-- reviews
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-frayed-jacket', 'Gabrielle N.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '30 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-frayed-jacket', 'Andre V.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '91 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-frayed-jacket', 'Wesley T.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '157 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-frayed-jacket', 'Kelly D.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '221 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-puffer', 'Kevin H.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '28 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-puffer', 'Malik A.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '32 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-puffer', 'Brianna E.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '127 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-puffer', 'Wesley T.', 4, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '155 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-puffer', 'Kelly D.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '202 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-tribal-tee', 'Ronald C.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '26 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-tribal-tee', 'Wesley T.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '59 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-tribal-tee', 'Marc-Andre P.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '160 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('ash-tribal-tee', 'Kevin H.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '223 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('aviator-sunglasses', 'Samantha L.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '166 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('aviator-sunglasses', 'Brianna E.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '189 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('aviator-sunglasses', 'Nadege F.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '203 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('aviator-sunglasses', 'Alicia M.', 3, 'Good but pricey', 'Quality is solid, just wish it was a bit more affordable.', now() - interval '226 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('beanie', 'Gabrielle N.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '33 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('beanie', 'Nadege F.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '59 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('beanie', 'Alicia M.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '182 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('bold-sunglasses', 'Samantha L.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '78 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('bold-sunglasses', 'Gabrielle N.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '109 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('bold-sunglasses', 'Wesley T.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '123 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('bold-sunglasses', 'Kevin H.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '187 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cargo-shorts', 'Alicia M.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '29 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cargo-shorts', 'Ronald C.', 4, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '50 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cargo-shorts', 'Malik A.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '104 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cargo-shorts', 'Brianna E.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '127 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cargo-shorts', 'Michaela J.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '144 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cargo-shorts', 'Devon K.', 4, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '218 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('chain-necklace', 'Malik A.', 3, 'Good but pricey', 'Quality is solid, just wish it was a bit more affordable.', now() - interval '77 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('chain-necklace', 'Wesley T.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '80 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('chain-necklace', 'Xavier Q.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '171 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('chain-necklace', 'Kevin H.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '204 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('chain-necklace', 'Ronald C.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '225 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('chain-necklace', 'Brianna E.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '231 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('classic-wash-denim', 'Samantha L.', 4, 'Good but pricey', 'Quality is solid, just wish it was a bit more affordable.', now() - interval '35 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('classic-wash-denim', 'Andre V.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '101 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('classic-wash-denim', 'Nadege F.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '116 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('classic-wash-denim', 'Kevin H.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '238 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cowl-hoodie', 'Priya S.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '7 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cowl-hoodie', 'Brianna E.', 4, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '42 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cowl-hoodie', 'Alicia M.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '92 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cowl-hoodie', 'Tiffany W.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '98 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cowl-hoodie', 'Jasmine R.', 4, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '102 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cowl-hoodie', 'Marc-Andre P.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '170 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-blazer', 'Priya S.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '120 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-blazer', 'Marc-Andre P.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '126 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-blazer', 'Gabrielle N.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '168 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-blazer', 'Jasmine R.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '181 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-blazer', 'Brianna E.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '181 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-boxy-tee', 'Kevin H.', 3, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '29 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-boxy-tee', 'Samantha L.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '99 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-boxy-tee', 'Nadege F.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '107 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-boxy-tee', 'Jasmine R.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '142 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-boxy-tee', 'Wesley T.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '145 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-puffer', 'Malik A.', 4, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '43 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-puffer', 'Jasmine R.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '59 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-puffer', 'Chris O.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '96 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-puffer', 'Wesley T.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '112 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-puffer', 'Kelly D.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '124 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-puffer', 'Junior B.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '126 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-trouser', 'Priya S.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '56 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-trouser', 'Ronald C.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '100 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-trouser', 'Tiffany W.', 3, 'Runs a bit big', 'Nice quality overall, but I''d size down if you want a more fitted look.', now() - interval '109 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-trouser', 'Nadege F.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '190 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('cream-trouser', 'Malik A.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '232 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crew-socks', 'Wesley T.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '132 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crew-socks', 'Marc-Andre P.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '150 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crew-socks', 'Brianna E.', 3, 'Runs a bit big', 'Nice quality overall, but I''d size down if you want a more fitted look.', now() - interval '153 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crew-socks', 'Alicia M.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '204 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crossbody-bag', 'Priya S.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '42 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crossbody-bag', 'Andre V.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '83 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('crossbody-bag', 'Gabrielle N.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '140 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('dark-indigo-denim', 'Gabrielle N.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '30 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('dark-indigo-denim', 'Andre V.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '91 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('dark-indigo-denim', 'Wesley T.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '157 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('dark-indigo-denim', 'Kelly D.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '221 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('denim-alline-skirt', 'Wesley T.', 4, 'Good but pricey', 'Quality is solid, just wish it was a bit more affordable.', now() - interval '64 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('denim-alline-skirt', 'Gabrielle N.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '98 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('denim-alline-skirt', 'Devon K.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '137 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('denim-alline-skirt', 'Chris O.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '176 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('denim-alline-skirt', 'Ronald C.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '219 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('double-emblem-hoodie', 'Kelly D.', 3, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '38 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('double-emblem-hoodie', 'Gabrielle N.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '123 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('double-emblem-hoodie', 'Jasmine R.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '135 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('frayed-hoodie-vest', 'Brianna E.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '49 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('frayed-hoodie-vest', 'Marc-Andre P.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '130 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('frayed-hoodie-vest', 'Malik A.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '143 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('frayed-hoodie-vest', 'Michaela J.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '155 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('frayed-hoodie-vest', 'Devon K.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '160 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-blazer', 'Alicia M.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '30 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-blazer', 'Gabrielle N.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '90 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-blazer', 'Ronald C.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '121 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-blazer', 'Chris O.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '166 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-tribal-tee', 'Ronald C.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '32 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-tribal-tee', 'Xavier Q.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '53 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-tribal-tee', 'Junior B.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '94 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('heritage-tribal-tee', 'Chris O.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '187 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('highwaist-skirt', 'Nadege F.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '33 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('highwaist-skirt', 'Tiffany W.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '163 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('highwaist-skirt', 'Malik A.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '203 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('highwaist-skirt', 'Kevin H.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '207 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('longline-puffer', 'Tiffany W.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '45 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('longline-puffer', 'Kevin H.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '169 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('longline-puffer', 'Samantha L.', 4, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '213 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('mini-backpack', 'Nadege F.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '41 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('mini-backpack', 'Tiffany W.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '100 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('mini-backpack', 'Andre V.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '122 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('mini-backpack', 'Marc-Andre P.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '185 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('mini-backpack', 'Michaela J.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '196 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('mini-backpack', 'Priya S.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '226 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('onyx-hoodie', 'Xavier Q.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '135 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('onyx-hoodie', 'Malik A.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '173 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('onyx-hoodie', 'Samantha L.', 3, 'Runs a bit big', 'Nice quality overall, but I''d size down if you want a more fitted look.', now() - interval '201 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('onyx-hoodie', 'Chris O.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '207 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('oversized-blazer', 'Malik A.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '51 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('oversized-blazer', 'Junior B.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '65 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('oversized-blazer', 'Nadege F.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '116 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('oversized-blazer', 'Samantha L.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '183 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('oversized-blazer', 'Xavier Q.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '202 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('oversized-blazer', 'Alicia M.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '239 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('palm-hooded-jacket', 'Andre V.', 4, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '70 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('palm-hooded-jacket', 'Gabrielle N.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '73 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('palm-hooded-jacket', 'Brianna E.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '225 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('palm-vest', 'Wesley T.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '91 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('palm-vest', 'Alicia M.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '105 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('palm-vest', 'Marc-Andre P.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '114 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pendant-chain', 'Gabrielle N.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '126 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pendant-chain', 'Nadege F.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '148 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pendant-chain', 'Michaela J.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '161 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pendant-chain', 'Tiffany W.', 3, 'Runs a bit big', 'Nice quality overall, but I''d size down if you want a more fitted look.', now() - interval '179 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pleated-skirt', 'Kelly D.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '24 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pleated-skirt', 'Xavier Q.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '122 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('pleated-skirt', 'Andre V.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '207 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('puffer-jacket', 'Michaela J.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '107 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('puffer-jacket', 'Tiffany W.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '144 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('puffer-jacket', 'Brianna E.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '209 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('quilted-vest', 'Priya S.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '58 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('quilted-vest', 'Malik A.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '109 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('quilted-vest', 'Devon K.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '122 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('quilted-vest', 'Samantha L.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '161 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('quilted-vest', 'Alicia M.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '178 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('quilted-vest', 'Kelly D.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '191 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('raw-black-denim', 'Ronald C.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '10 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('raw-black-denim', 'Samantha L.', 4, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '144 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('raw-black-denim', 'Brianna E.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '216 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('relaxed-black-shorts', 'Samantha L.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '58 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('relaxed-black-shorts', 'Kelly D.', 3, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '64 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('relaxed-black-shorts', 'Ronald C.', 5, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '68 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('relaxed-black-shorts', 'Priya S.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '95 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('relaxed-black-shorts', 'Kevin H.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '112 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('relaxed-black-shorts', 'Nadege F.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '181 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('shop-the-fit', 'Andre V.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '90 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('shop-the-fit', 'Nadege F.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '138 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('shop-the-fit', 'Gabrielle N.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '196 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('signature-icon-tee', 'Samantha L.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '15 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('signature-icon-tee', 'Tiffany W.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '93 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('signature-icon-tee', 'Priya S.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '138 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('slate-vest', 'Junior B.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '152 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('slate-vest', 'Devon K.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '218 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('slate-vest', 'Tiffany W.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '225 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('slate-vest', 'Ronald C.', 5, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '237 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('snapback-cap', 'Brianna E.', 5, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '5 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('snapback-cap', 'Priya S.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '32 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('snapback-cap', 'Michaela J.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '76 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('snapback-cap', 'Samantha L.', 4, 'Obsessed', 'Wasn''t expecting the quality to be this good for the price. Fits exactly like the pictures and the material feels heavy-duty.', now() - interval '97 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('snapback-cap', 'Chris O.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '150 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('snapback-cap', 'Alicia M.', 4, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '151 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('studded-belt', 'Chris O.', 4, 'Worth it', 'A little pricier than I expected but the quality justifies it completely.', now() - interval '112 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('studded-belt', 'Gabrielle N.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '133 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('studded-belt', 'Brianna E.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '210 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('tote-bag', 'Marc-Andre P.', 5, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '32 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('tote-bag', 'Gabrielle N.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '41 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('tote-bag', 'Wesley T.', 3, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '51 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('tote-bag', 'Ronald C.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '186 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('tote-bag', 'Nadege F.', 4, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '189 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('tote-bag', 'Devon K.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '203 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('vintage-cream-shorts', 'Devon K.', 3, 'Solid piece', 'Not bad at all, though the color was slightly different than pictured on my screen.', now() - interval '40 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('vintage-cream-shorts', 'Junior B.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '106 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('vintage-cream-shorts', 'Andre V.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '154 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wash-denim-shorts', 'Jasmine R.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '116 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wash-denim-shorts', 'Gabrielle N.', 4, 'Better in person', 'The detailing is way more impressive in person. Definitely a statement piece.', now() - interval '221 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wash-denim-shorts', 'Kelly D.', 4, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '234 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('web-belt', 'Michaela J.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '105 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('web-belt', 'Kevin H.', 5, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '114 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('web-belt', 'Kelly D.', 5, 'Never basic indeed', 'This is exactly the vibe I was looking for. Gets compliments every time I wear it.', now() - interval '143 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('web-belt', 'Tiffany W.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '189 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wide-leg-denim', 'Michaela J.', 3, 'Runs a bit big', 'Nice quality overall, but I''d size down if you want a more fitted look.', now() - interval '80 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wide-leg-denim', 'Samantha L.', 4, 'Perfect fit', 'Runs true to size for me, oversized in the way I wanted without being sloppy.', now() - interval '139 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wide-leg-denim', 'Devon K.', 5, 'True to size', 'Ordered my usual size and it fit perfectly. Already planning my next order.', now() - interval '160 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wide-leg-denim', 'Andre V.', 4, 'Fast shipping too', 'Came quicker than expected and packaging was clean. Product itself is great.', now() - interval '197 days');
INSERT INTO reviews (product_id, name, rating, title, body, created_at) VALUES ('wide-leg-denim', 'Wesley T.', 5, 'Comfortable and heavy duty', 'You can tell this isn''t some thin fast-fashion material. Holds up after multiple washes.', now() - interval '240 days');
